### ISSUE TITLE
Missing skybox/IBL texture by default

### ISSUE THREAD

**Issue by Kliaxe** [enjiushi/VulkanLearn#1]
First of all, I just want to say that, your project is amazing! I’m generally new to game engine structures and the graphics API, Vulkan. Keep up the extremely good work!

Right after I saw your GitHub project, I thought to myself I really had to try and build it. So I ran  CMake and tried to build. The CMake ran fine, and generated the .sln file successfully. Then I jumped into Visual Studio and started to build. However, I ran into an issue;

I was getting this access violation in file: 'storage_linear.inl'
![image](https://user-images.githubusercontent.com/16865975/62834097-0475b180-bc48-11e9-8cbe-8cb0f1658c67.png)

It turns out the texture '../data/textures/hdr/gcanyon_cube.ktx', doesn't exist in the actual project. 

The texture is called in 'VulkanGlobal .cpp':
`gli::texture_cube gliSkyBox(gli::load("../data/textures/hdr/gcanyon_cube.ktx"));
	UniformData::GetInstance()->GetGlobalTextures()->InitIBLTextures(gliSkyBox);`

**Comment by enjiushi** [comment]
Let me add this file, sorry for the bug. I only ran on my own pc:)

**Comment by enjiushi** [comment]
Resolved.

This giant texture is from sascha willems's vulkan repository. He uses a python script to download a set of textures(http://vulkan.gpuinfo.org/downloads/vulkan_asset_pack.zip). I might do the same.
