### ISSUE TITLE
Unstable frame interval

### ISSUE THREAD

**Issue by Kliaxe** [enjiushi/VulkanLearn#4]
Hi @enjiushi 

Regarding the unstable frame interval, I can confirm it's evident.

I found something very interesting. Out of curiosity, I commented the whole physical device present mode search, in 'SwapChain.cpp':

![image](https://user-images.githubusercontent.com/16865975/63893111-98d26900-c9e9-11e9-967d-c09c60b32892.png)

And suddenly, the problem disappeared! I have no glue how/why it worked right now. Thought it could be interesting for you to check out, to see if it makes any difference on your PC.

**Comment by Kliaxe** [comment]
In SachaWilliams' 'Vulkan' git, it looks like he prioritised the "VK_PRESENT_MODE_FIFO_KHR", until the user chooses to disable v-sync:

https://github.com/SaschaWillems/Vulkan/blob/2f985f2aaea6a46146dc3d80f0b806defbd24a33/base/VulkanSwapChain.hpp#L317-L337

Tbh. it could be something completely unrelated, but it could probably be something I hope.

**Comment by enjiushi** [comment]
Damn man, that's magic you found!

I spent some time thinking about this. The reason could be:

Mail box mode will present latest rendered frame. However the bad thing
here is that which frame will be presented to screen is highly unpredicted.
It could be very close to a vsync point, or very far. This phenomenon gives
me the feeling of frame juddering.
With fifo mode, demo spends around 5ms(debug version, on my pc) per frame,
eventually a frame will stuck when acquiring a new image from swapchain
util a frame is present on screen and an image is free. And that'll create
a perfect rhythm that each frame spends approximately 16.66666...ms, a
vsync interval.

I wanna change fifo as default present mode.

Thanks for the found again!

Kliaxe <notifications@github.com> 于2019年8月29日周四 上午5:40写道：

**Comment by enjiushi** [comment]
Resolved as @Kliaxe did

883d1fb
